package dao.cacao.dnd5sheet.domain.model

data class Sheet(
    val id: Long,
    val level: Int?,
    val characterName: String?,
    val characterRace: String?,
    val characterClass: String?,
//    val alignment: String,
//    val playerName: String,
//    val background: String,
//    val inspiration: Boolean,
//    val proficiencyBonus: Int,
    val strength: Int?,
    val dexterity: Int?,
    val constitution: Int?,
    val intelligence: Int?,
    val wisdom: Int?,
    val charisma: Int?,
//    val savingThrows: List<Boolean>,
//    val skills: List<Skill>,
//    val passivePerception: Int,
//    val armorClass: Int,
//    val hitDice: Int,
//    val maxHp: Int,
//    val tempHp: Int,
//    val currentHitPoInts: Int,
//    val initiative: Int,
//    val speed: Int,
//     val deathSaves,
//     val attackAndSpellCasting,
//     val featuresAndTraits,
//     val inventoryAndEquipment,
//     val otherProficienciesAndLanguages
)